### ISSUE TITLE
[Bug] Modals confirmation buttons not closing the modal after clicking

### ISSUE THREAD

**Issue by hugocostadev** [RocketChat/Apps.QuickReplies#11]
### What happened?

I've noticed that the create/edit/delete reply modal is not closing when we click the confirmation button

### Relevant ScreenShots

 ![image](https://github.com/user-attachments/assets/7878b011-db3d-4755-bd87-02ff6fb90893)
![image](https://github.com/user-attachments/assets/bce95271-b7b2-4800-93e1-3dd55ec891fb)

### Version

v0

### What browsers are you seeing the problem on?

Chrome

**Comment by VipinDevelops** [comment]
Hey @hugocostadev I guess there is a Update In App engine that now you can only handle one UI update, so we can only update list of replies in real time like we have or we can close the modal.

we can add a button in list like refresh to update it ? or 2 buttons maybe on for add new replies and one to refresh.

what you think

**Comment by VipinDevelops** [comment]
![image](https://github.com/user-attachments/assets/e3fe781f-5cf2-4fcf-bc5a-5dc0fc2eb0b0)
