### ISSUE TITLE
[Bug] cannot scroll to see other messages for /qs 

### ISSUE THREAD

**Issue by hugocostadev** [RocketChat/Apps.QuickReplies#14]
### What happened?

Can't see all messages in `/qs`
It should appear a horizontal scroll, as the giphy app
![image](https://github.com/user-attachments/assets/fc16afce-4f89-4a2f-a8ff-f048235e5b51)

### Steps to reproduce

use the slack command: `/qs` 
Can't see all messages

### Relevant ScreenShots

![image](https://github.com/user-attachments/assets/284df046-f821-4c9a-a2ff-fc9049334186)

### Version

v0

### What browsers are you seeing the problem on?

Chrome

**Comment by VipinDevelops** [comment]
Hey @hugocostadev  
We already have this feature I am limiting the search results to the top 5 and character length to 35 so, so we can avoid buggy UI.

![image](https://github.com/user-attachments/assets/113ea31d-4a80-4141-b73f-38f74d58be36)

with Too many Preview, the UI starts to look Weird 
![image](https://github.com/user-attachments/assets/5201f870-bb34-4885-b68c-1212ce6d53a0)
