### ISSUE TITLE
Deployment Error, App API version is Outdated

### ISSUE THREAD

**Issue by Devansht420** [RocketChat/Apps.QuickReplies#20]
### What happened?

While starting a server using the latest version of Rocket.Chat and deploying apps to it, I encountered an error: the app API version was out of date.

I've tried working on the issue and seemed to have fixed it, I'm willing to submit a pull request for the same.
Please let me know if the issue is reproducible so that it can be fixed, as it will help new users and developers to have a smoother and hassle free experience.

### Steps to reproduce

- Install the latest version of [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat)
- Install the latest version of [Apps.QuickReplies](https://github.com/RocketChat/Apps.QuickReplies) 
- Start the server 
- Deploy the App

### Relevant ScreenShots

![image](https://github.com/user-attachments/assets/f6ade568-fd41-4711-933f-93b9da067912)

### Version

7.1.0

### What browsers are you seeing the problem on?

Chrome

**Comment by VipinDevelops** [comment]
Thanks for finding this out @Devansht420 You can go ahead and solve this issue and make documentation changes for the same.
